"""add transaction tables

Revision ID: cad41f63cb90
Revises: e1a896741781
Create Date: 2025-06-08 18:05:11.910797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cad41f63cb90'
down_revision: Union[str, None] = 'e1a896741781'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('TRD_ID', sa.Integer(), nullable=False),
    sa.Column('DATETIME', sa.DateTime(), nullable=True),
    sa.Column('EMP_CD', sa.String(length=10), nullable=True),
    sa.Column('STORE_CD', sa.String(length=5), nullable=True),
    sa.Column('POS_NO', sa.String(length=3), nullable=True),
    sa.Column('TOTAL_AMT', sa.Integer(), nullable=True),
    sa.Column('TTL_AMT_EX_TAX', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('TRD_ID')
    )
    op.create_index(op.f('ix_transaction_TRD_ID'), 'transaction', ['TRD_ID'], unique=False)
    op.create_table('transaction_detail',
    sa.Column('TRD_ID', sa.Integer(), nullable=False),
    sa.Column('DTL_ID', sa.Integer(), nullable=False),
    sa.Column('PRD_ID', sa.Integer(), nullable=True),
    sa.Column('PRD_CODE', sa.String(length=13), nullable=True),
    sa.Column('PRD_NAME', sa.String(length=50), nullable=True),
    sa.Column('PRD_PRICE', sa.Integer(), nullable=True),
    sa.Column('TAX_CD', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['TRD_ID'], ['transaction.TRD_ID'], ),
    sa.PrimaryKeyConstraint('TRD_ID', 'DTL_ID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_detail')
    op.drop_index(op.f('ix_transaction_TRD_ID'), table_name='transaction')
    op.drop_table('transaction')
    # ### end Alembic commands ###
