"""init

Revision ID: e1a896741781
Revises: 
Create Date: 2025-06-08 17:58:27.296075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1a896741781'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_master',
    sa.Column('PRD_ID', sa.Integer(), nullable=False),
    sa.Column('CODE', sa.Integer(), nullable=False),
    sa.Column('NAME', sa.String(length=50), nullable=True),
    sa.Column('PRICE', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('PRD_ID'),
    sa.UniqueConstraint('CODE')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_master')
    # ### end Alembic commands ###
